version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    networks:
      - qdrant_network

  rust_app:
    build:
      context: .
    depends_on:
      - qdrant
    networks:
      - qdrant_network

networks:
  qdrant_network:
